### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by l0kihardt** [blukat29/blukat29.github.io#1]
hi, yujong:

       I just read your writeup about challenge meow in codegate-2017-quals.
       http://blukat29.github.io/2017/02/codegate-2017-quals-meow/   
       I didnt use angr when I was solving this challenge. After I read your blog, I tried to solve it with angr, but I meet up with this problem
![image](https://cloud.githubusercontent.com/assets/17106348/23195525/ff5b5fa2-f8ee-11e6-8388-d82dc816a166.png)
            it seems that it cant execute to the 0x13c4.I wonder how do you go there???

**Comment by blukat29** [comment]
You should start from 0x400d1d and run to 0x4013c4. As the warning message says, the binary is loaded at 0x400000. If this does not solve the problem, try setting the registers to reasonable values.

p.s. please send questions or comments through my email or comment section on the blog.
