### ISSUE TITLE
Consider adding Disqus (or likewise) to your posts

### ISSUE THREAD

**Issue by ADTC** [blukat29/blukat29.github.io#2]
Have you considered adding Disqus commenting system or something similar to your blog posts?

Anyway I want to thank you for the guide for Building Android App without IDE. I'm going to try it out, because I find Android Studio (or IntelliJ for that matter) to be so heavy on the system. And I hate that it starts an emulator when I just need to get the APK file.

**Comment by blukat29** [comment]
Thanks for the issue. There was disqus comment but it was not working due to a minor mistake. I also appreciate your input. Happy that it helped.
